version: '3.8'
services:
  db:
    image: timescale/timescaledb:2.10.1-pg14
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-volcanic_dev_password}
      POSTGRES_DB: volcanic_historical
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7.0.8
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
