name: Dependency Updates

on:
  schedule:
    - cron: '0 2 * * 1'  # Every Monday at 2 AM UTC
  workflow_dispatch:

jobs:
  update-python-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
    
    - name: Update Python dependencies
      working-directory: ./backend
      run: |
        poetry update
        poetry export -f requirements.txt --output requirements.txt
    
    - name: Create Pull Request for Python updates
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update Python dependencies'
        title: 'chore: update Python dependencies'
        body: |
          Automated dependency update for Python packages.
          
          Please review the changes and ensure all tests pass before merging.
        branch: dependency-updates/python
        delete-branch: true

  update-node-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Update Node dependencies
      working-directory: ./frontend
      run: |
        npm update
        npm audit fix --audit-level moderate
    
    - name: Create Pull Request for Node updates
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update Node.js dependencies'
        title: 'chore: update Node.js dependencies'
        body: |
          Automated dependency update for Node.js packages.
          
          Please review the changes and ensure all tests pass before merging.
        branch: dependency-updates/node
        delete-branch: true
